# -- mode: ruby --
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "nms" do |nms|
    nms.vm.box = "centos/7"
    nms.vm.hostname = "nms"
    nms.vm.network "private_network", ip: "192.168.88.3"
    nms.vm.network "forwarded_port", guest: 8080, host: 8080
    nms.vm.network "forwarded_port", guest: 69, host: 69
    nms.vm.network "forwarded_port", guest: 3000, host: 3000
    nms.vm.network "forwarded_port", guest: 9090, host: 9090 
    nms.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--name", "nms"]
    end
    nms.vm.provision 'file', source: 'scripts/', destination: 'src/'
    #nms.vm.provision 'shell', path: 'scripts/setup_2.sh'
  end
end
